title: "./RNDTX"
description: "tail -f /dev/brain » /www"
about: "I'm a bit of a hacker fanatic and know a fair bit about that industry and cyber crime and cyber warfare. "
location: "Indonesia, Tangerang"
email: rndtx@dracos-linux.org
baseurl: ""
url: "https://nullrndtx.github.io"
twitter_username: nullrndtx
github_username:  nullrndtx
author: "Randall Tux"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname: nullrndtx

# language settings
isolang: us
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
